### ISSUE TITLE
Suggestion - Charged copper and gunpowder

### ISSUE THREAD

**Issue by Kiryonn** [Safrodev/oxidized#1]
So i wanted to make a suggestion to add some mechanics to copper.

### CHARGED COPPER BLOCK
When a lighnting strike hits a copper rod, if there is a copper block (of any kind) under it, it will 'charge' the block.

In my head the charged copper would be kind of white depending of the weathered effect and you could uncharge it by rightclicking with gunpowder gaining charged gunpowder. if you don't want it you could always get rid of it and since gunpowder is quite common, it won't be that much of a waste.

### CHARGED GUNPOWDER
with that powder, you could
* craft a bit more powerfull tnt (charged tnt) - crafted with tnt in the middle and charged gunpowder on N, S, E, and W
* craft a charged gunpowder block - crafted with 9 charged gunpowder

you could also obtain that powder by killing charged creepers

### CHARGED GUNPOWDER BLOCK
would be used to power the copper rails instead of using redstone. That way the 100 blocks would be balanced since it's a bit of work to make it. And i was thinking that maybe it could be used as a light source too

**Comment by Safrodev** [comment]
Ooh nice ideas! I will consider adding these soon!
