### ISSUE TITLE
Recipes are not unlocked when items required for them are obtained.

### ISSUE THREAD

**Issue by AstralOrdana** [Safrodev/oxidized#10]
The recipes for the blocks and items in this mod do not show up in the recipe book until after you craft them for the first time which makes it hard for players to know what to do without looking it up. If you don't know how to do this or you'd just like someone else to do it, I would be happy to help as I have experience with recipe advancements.

**Comment by Safrodev** [comment]
Thanks for reporting, I’ll get these added in an upcoming small patch.
