### ISSUE TITLE
The Copper Button recipe conflicts with a vanilla Minecraft recipe.

### ISSUE THREAD

**Issue by Vaelzan** [Safrodev/oxidized#13]
Recipe: https://github.com/Safrodev/oxidized/blob/e0573328df86052c358d2546a0f8ef37dc676ab0/src/main/resources/data/oxidized/recipes/copper_button.json

Copper blocks (and all metal blocks) are already used as the sole ingredient in a shapeless crafting recipe in vanilla Minecraft - to convert them back into ingots.

In my own modpack I have resolved this conflict by changing the recipe to any one plank (by tag), and one copper ingot (as a shapeless recipe) - that matches the form used by mods like Quark (for their iron and gold buttons), so should be intuitive to people who have played modded Minecraft for a while. I figure that it makes sense to also make this change in the mod itself so that other players / pack developers don't have to make a similar change to avoid the conflict.

**Comment by Safrodev** [comment]
Yep someone has already reported this on my discord server. It was a silly mistake from me and I will release a patch soon.
