### ISSUE TITLE
Suggestion: More config options

### ISSUE THREAD

**Issue by laceflowermc** [Safrodev/oxidized#18]
I have a couple suggestions for addition config options that increase the modularity of the mod. I'd find a couple of these useful, hopefully others would too.
- enable copper pan
- enable copper pulsar
- enable kiln
- enable blocks

**Comment by Safrodev** [comment]
Nice suggestion, I'll add these in the next release.

**Comment by Safrodev** [comment]
Sorry about the change but configs for blocks causes a lot of issues due to minecraft using tags in 1.18+ for mining. Disabling a block would cause blocks mined with pickaxes to not drop anything.
