### ISSUE TITLE
copper rail render

### ISSUE THREAD

**Issue by Kiryonn** [Safrodev/oxidized#2]
I think you forgot to add the activated copper rail render when in diags:
![activated](https://user-images.githubusercontent.com/60699390/126853167-aba0b914-9add-4a6c-aef3-2cf53c9b039f.png)
![normal](https://user-images.githubusercontent.com/60699390/126853186-aa4eed89-8a65-4758-b9eb-8cd45cbf7ff1.png)

**Comment by Safrodev** [comment]
I am aware of this issue and it will be fixed in an update releasing tomorrow (July 23rd)
