### ISSUE TITLE
Causes Fabric Waystones to be unbreakable

### ISSUE THREAD

**Issue by KMFrench1** [Safrodev/oxidized#20]
[Oxidized 1.6.0 (1.18.1)] Causes waystones (https://www.curseforge.com/minecraft/mc-mods/fabric-waystones) to be unbreakable, If you do mine them they don't drop the waystone.
Fabric 1.18.1

**Comment by Safrodev** [comment]
I’m aware of this issue. I’m working on it, but it may not be possible to fix on my end. This can be temporarily fixed by enabling rose gold tools in the config though.

**Comment by Safrodev** [comment]
Fixed in 1.6,1
