### ISSUE TITLE
Vertical Cut copper blocks not oxidizing

### ISSUE THREAD

**Issue by BinxetyBinx** [Safrodev/oxidized#26]
Playing on Better Minecraft (FABRIC) for 1.18.2 v9

As stated in the title, I'm building a structure purely out of copper blocks, it's been several real life days and even more in minecraft days and the copper blocks from your mod specifically are not oxidizing even though all the other ones are. Submitted a picture to show that the other blocks are changing while yours are not.

![2022-05-27_13 59 03](https://user-images.githubusercontent.com/47510715/170774419-52c4a67a-31f7-427e-9be6-b9d59bfd9151.png)

**Comment by Safrodev** [comment]
Should be fixed in 1.7.0 sorry about this
