### ISSUE TITLE
[Suggestion] Copper Furnace can't do glass from red sand

### ISSUE THREAD

**Issue by variety754** [Safrodev/oxidized#33]
Copper Furnace working on sand, but with red sand it's not. I think it'll be better to add red sand to the possible glass sources in this furnace.

**Comment by jshipley** [comment]
In 1.19.4 a "minecraft:smelts_to_glass" tag was added. Replacing `"item": "minecraft:sand"` with `"tag": "minecraft:smelts_to_glass"` in the glass_kiln_smelting.json recipe should be all that is needed for 1.19.4+.

For older minecraft versions (if they're still supported), you could just add in the minecraft:smelts_to_sand tag in the data folder.

**Comment by Safrodev** [comment]
Yep, this fix is coming with the 1.20 update
