### ISSUE TITLE
[Suggestion] Copper Pulsar - texture indicator when is activated

### ISSUE THREAD

**Issue by bafb** [Safrodev/oxidized#40]
It causes me a lot of stress and headaches not to know when I have the copper pulsar activated, I have to open the chat history or activate it and deactivate it again, it is very annoying.
I use the copper pulsar a lot (and possibly many users of the mod too) and it wouldn't be bad if it had a different texture (in the inventory and in the hand) to know when it is activated (like when a crossbow has an arrow for example), it could be something as simple as the redstone tips glowing (or something more fancy and elaborate like an animation on the tips of waves that represent the electromagnetic field).

**Comment by Safrodev** [comment]
Yeah, this is something that has bothered me too but I keep forgetting to add it in. I can definitely add this in along with a tooltip to show the status.

**Comment by bafb** [comment]
i still waiting for that man :c

**Comment by bafb** [comment]
i still waiting for that man :c
