### ISSUE TITLE
Mismatching mod

### ISSUE THREAD

**Issue by YejiYeah** [Safrodev/oxidized#43]
The mod Oxidized Fabric 1.20.1, is installed in both, my server and my client, however the server doesn't allow us to log in, keeps sending the error that the mod is mismatching. Please help

**Comment by Safrodev** [comment]
That means your server and client do not have the same version of Oxidized. Check that the file name is exactly the same version.

**Comment by SaraXianLin** [comment]
yes, both have the same name, it's weird because the mod has not been updated an I was able to join the server before
![image](https://github.com/Safrodev/oxidized/assets/77309538/c6d79871-0575-46ab-91c2-34d8a8f5740a)
