### ISSUE TITLE
[bug] Parsing errors loading recipes

### ISSUE THREAD

**Issue by TobiPeterG** [Safrodev/oxidized#5]
The game log contains errors about parsing errors of recipes, e.g.:
```
[Render thread/ERROR]: Parsing error loading recipe oxidized:copper_lantern
com.google.gson.JsonSyntaxException: Unknown item tag 'c:copper_nuggets'
```
[latest.log](https://github.com/Safrodev/oxidized/files/7111460/latest.log)

Also, I noticed that it has the folowing error message in it:
`[Worker-Main-4/ERROR]: Couldn't load tag c:copper_nuggets as it is missing following references: techreborn:copper_nugget (from Oxidized),workings:copper_nugget (from Oxidized)`

**Comment by Safrodev** [comment]
Yes I am aware that happens. It should not crash you're game and it simply does that so tech reborn and workings copper nuggets work with recipes when they are installed. If it stops you from crafting anything please let me know and I can fix it easily.

**Comment by TobiPeterG** [comment]
> Yes I am aware that happens. It should not crash you're game and it simply does that so tech reborn and workings copper nuggets work with recipes when they are installed. If it stops you from crafting anything please let me know and I can fix it easily.

Nono, it doesn't crash the game, don't worry, it's just appearing in the log and I thought it might be worth noting

**Comment by Safrodev** [comment]
Oh okay that's good, I will also be fixing this log error in an upcoming patch.
