### ISSUE TITLE
Invalid Player Data

### ISSUE THREAD

**Issue by CammiePone** [Safrodev/oxidized#6]
Something in the latest update for Oxidized is now causing the game to throw Invalid Player Data errors whenever I try and join a world I had already joined at least once before.

The logs aren't particularly helpful, but I'll send it regardless. I only found out it was Oxidized by doing a binary search.

https://pastebin.com/zuhbwKdb

**Comment by Safrodev** [comment]
I know this is an extremely late reply but after some viewing I found that this error was not consistent with any other users. If the error is still occurring for you at this time, it may be due to a corrupt world or another issue.

**Comment by CammiePone** [comment]
Only reason I even attempted removing Oxidised is because a friend of mine brought up it causing issues for him, and lo and behold removing it from the pack fixed the issue.

What the problematic code is, I couldn't say. This really just seems to be a catch-all error Mojang likes to spew, without giving any useful information. Someone should really just make a mod that tells you exactly what the invalid data is.

**Comment by Safrodev** [comment]
No need to apologize, i appreciate you reporting the issue. I’ve just been a bit confused since the logs are a bit vague and this issue hasn’t been appearing for other users as far as I’m aware. For the meantime, it’d just be best to not use the mod until I can figure out what this issue is.
